### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by kintaro1981** [lheredias/Luftmensch#4]
I'm trying to install it on a Win10 21H1 machine and I'm getting this error:

```
Traceback (most recent call last):
  File "C:\Users\lenin\.conda\envs\luft\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\rthooks\pyi_rth_certifi.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: DLL load failed while importing _ssl: Impossibile trovare la procedura specificata.

```

The machine doesn't have a C:\Users\lenin\

**Comment by lheredias** [comment]
> I'm trying to install it on a Win10 21H1 machine and I'm getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\lenin\.conda\envs\luft\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\rthooks\pyi_rth_certifi.py", line 13, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
>   File "ssl.py", line 98, in <module>
> ImportError: DLL load failed while importing _ssl: Impossibile trovare la procedura specificata.
> ```
> 
> The machine doesn't have a C:\Users\lenin\

Please try with this link: https://github.com/lheredias/betas/releases/tag/v1.0

**Comment by JVKeller** [comment]
Just came across this looking for a PDF compressor. Installed on Win11 with no problems. 
Works good! Compression is good and it doesn't convert text to images like some of the other I've tested.

Great job @lheredias !

All this needs to me is batch ability...
